name: Build & Publish

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'next*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 13.x
        uses: actions/setup-node@master
        with:
          node-version: 13.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      # Publish with STABLE
      - name: Publish NPM latest
        if: startsWith(github.ref, 'refs/tags/v') # run only with tag
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Publish with NEXT tag
      - name: Publish NPM next!
        if: github.ref == 'refs/heads/next' # run only with NEXT branch
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Deploy Github Pages (only with v* tag)
      - name: Prepare Github Pages
        if: startsWith(github.ref, 'refs/tags/v') # run only with tag
        run: cp -r dist/ demo/dist/

      - name: Deploy Github Pages
        if: startsWith(github.ref, 'refs/tags/v') # run only with tag
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./demo
